#!/bin/sh
set -e

while [ $# -gt 0 ]; do
    case "$1" in
        --help|-h)
        echo "Usage: aws-switch [--help|-h] PROFILE"
        exit 0
        ;;
    esac
    ACCOUNT="$1"
    shift
done

if [ -z "$ACCOUNT" ]; then
    echo "Error: No account set!"
    echo "Usage: aws-switch [--help|-h] PROFILE"
    exit 1
fi

echo "Switching to AWS profile $ACCOUNT..."

if command -v aws-vault 1>/dev/null 2>&1; then
    export AWS_SWITCH_PROFILE="$ACCOUNT"
    aws-vault exec "$ACCOUNT" -- "$SHELL"
	export AWS_SWITCH_PROFILE=
else
	echo "Error: You must have aws-vault installed, see https://github.com/99designs/aws-vault"
	exit 1
fi
